#ifndef __ANTILAG_MANAGER_H__
#define __ANTILAG_MANAGER_H__

enum ANTI_LAG_FEATURE
{
	ANTI_LAG_HIDE_WINGS = 0,
	ANTI_LAG_HIDE_EFFECTS,
	ANTI_LAG_HIDE_ITEMS,
	ANTI_LAG_HIDE_PETS,
	ANTI_LAG_HIDE_MOUNT,
	ANTI_LAG_HIDE_CHARACTER,
	ANTI_LAG_HIDE_MONSTER,
	ANTI_LAG_HIDE_MAP_OBJECT,
	ANTI_LAG_HIDE_BACKGROUND,
	ANTI_LAG_FEATURE_COUNT
};

bool AntiLag_IsHidden(ANTI_LAG_FEATURE feature);
void AntiLag_UpdateHotkeys();

#endif // __ANTILAG_MANAGER_H__